name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  simple_animations: ^5.0.0+3
  # http: ^0.12.0+2
  # email_auth: ^0.0.1
  # firebase_core:
  # firebase_auth:
  # shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
